/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2018-05-02 18:22:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AllFiles.JSP.DataOwner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


       HttpSession session = null;
       String username = "";
       int id = 0;
       UserDAO userDAO = null;
       

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("   \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title></title>\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/menu.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" ");
      out.write('\n');

      session = request.getSession();

       if(session != null)
       {
    	   username = session.getAttribute("username").toString();
       }
       
      userDAO = UserDAO.getInstance();
      
      id = userDAO.getID1(username);
      System.out.println("Owner Id"+id);
       

      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("    body \n");
      out.write("    {\n");
      out.write("      background-image:url('bg.jpg');\n");
      out.write("    \n");
      out.write("        background-repeat: no-repeat;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("\n");
      out.write("<center><IMG SRC=\"");
      out.print(request.getContextPath());
      out.write("/header.png\" style=\"height:90px;width:950px;\"></center>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("<nav class=\"menu animated flipInX\">\n");
      out.write("\n");
      out.write("\t\t<ul class=\"ul\">\n");
      out.write("   \n");
      out.write(" \n");
      out.write(" <div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">Profile</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/OwnerProfile\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View Profile</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\" href=\"");
      out.print(request.getContextPath() );
      out.write("/EditOwnerProfile?username=");
      out.print(username );
      out.write("&no=1\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>Edit Profile</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\" href=\"");
      out.print(request.getContextPath() );
      out.write("/ChangeOwnerPassword?no=1&id=");
      out.print(id );
      out.write("\" target=\"myIframe\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>Change Password</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" <div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">Users</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/ListUser?submit=get\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View User Details</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" <div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">View Request</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/ViewRequest\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View User Request</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">File Upload</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\" href=\"");
      out.print(request.getContextPath());
      out.write("/AllFiles/JSP/Admin/upload_file.jsp\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>Upload File</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\" href=\"");
      out.print(request.getContextPath());
      out.write("/UploadFileList?submit=get\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View Details</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">File Access Control</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/AllFiles/JSP/Admin/access_control.jsp\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>Control File Access</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/AccessFileControlList?submit=get\"  target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View Access Control </h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class =\"link\">    \n");
      out.write(" <h4><font style=\"font-family: monotype corsiva;font-size: 25px;\">Transactions</font></h4>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/UploadFileList?submit=get\" target=\"myIframe\">\n");
      out.write("\t\t\t\t<h3>View Transactions</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class =\"link\">      \n");
      out.write("\t\t\t<a class=\"a\"  href=\"");
      out.print(request.getContextPath());
      out.write("/Logout\" >\n");
      out.write("\t\t\t\t<h3>Logout</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t</nav>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"position:absolute;top:130px;left:300px;\">\n");
      out.write("\t<iframe align=\"middle\"  style=\"margin-left: 60px;\" \n");
      out.write("\tframeborder=\"0\" scrolling=\"auto\" name=\"myIframe\" height=\"930px\" width=\"800px\"></iframe>\n");
      out.write("</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
