/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2018-05-02 12:34:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.dao.UserDAO;
import com.dao.DAO;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Cloud TAFC Project</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t<link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"color/default.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- <link rel=\"shortcut icon\" href=\"img/favicon.ico\"> -->\r\n");
      out.write("\t<!-- =======================================================\r\n");
      out.write("    Theme Name: Maxim\r\n");
      out.write("    Theme URL: https://bootstrapmade.com/maxim-free-onepage-bootstrap-theme/\r\n");
      out.write("    Author: BootstrapMade.com\r\n");
      out.write("    Author URL: https://bootstrapmade.com\r\n");
      out.write("\t======================================================= -->\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("  function checkvariability()\r\n");
      out.write("    {\r\n");
      out.write("    \tdocument.getElementById(\"contact\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"services\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.getElementById(\"works\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"working\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    function checkvariability1()\r\n");
      out.write("    {\r\n");
      out.write("    \tdocument.getElementById(\"contact\").style.display=\"\";\r\n");
      out.write("    \tdocument.getElementById(\"services\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.getElementById(\"works\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"working\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    function checkvariability2()\r\n");
      out.write("    {\r\n");
      out.write("    \tdocument.getElementById(\"contact\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"services\").style.display=\"\";\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.getElementById(\"works\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"working\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    function checkvariability3()\r\n");
      out.write("    {\r\n");
      out.write("    \tdocument.getElementById(\"contact\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"services\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.getElementById(\"works\").style.display=\"\";\r\n");
      out.write("    \tdocument.getElementById(\"working\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    function checkvariability4()\r\n");
      out.write("    {\r\n");
      out.write("    \tdocument.getElementById(\"contact\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"services\").style.display=\"none\";\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.getElementById(\"works\").style.display=\"none\";\r\n");
      out.write("    \tdocument.getElementById(\"working\").style.display=\"\";\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- navbar -->\r\n");
      out.write("\t<div class=\"navbar-wrapper\">\r\n");
      out.write("\t\t<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<!-- Responsive navbar -->\r\n");
      out.write("\t\t\t\t\t<!-- <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span> -->\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          <div class=\"brand\" style=\"position: fixed; top: -15px; left: 115x; \">\r\n");
      out.write("            <a href=\"index.jsp\"><h1><b>TAFC: Time and Attribute Factors Combined Access Control on Time-Sensitive Data in Public Cloud</b></h1></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </br></br> </br></br>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t\t\t\t\t<!-- navigation -->\r\n");
      out.write("\t\t\t\t\t<nav class=\"pull-right nav-collapse collapse\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"menu-main\" class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t <li><a title=\"header-wrapper\" href=\"#header-wrapper\" onclick=\"checkvariability();\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a title=\"contact\" href=\"#contact\" onclick=\"checkvariability1();\">Central Authority</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a title=\"services\" href=\"#services\" onclick=\"checkvariability2();\">Owner</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a title=\"works\" href=\"#works\" onclick=\"checkvariability3();\">User</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a title=\"working\" href=\"#working\" onclick=\"checkvariability4();\">User Registration</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Header area -->\r\n");
      out.write("\t<div id=\"header-wrapper\" class=\"header-slider\">\r\n");
      out.write("\t\t<header class=\"clearfix\">\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<!-- <img src=\"img/logo-image.png\" alt=\"\" /> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- end spacer section -->\r\n");
      out.write("\t<!-- section: contact -->\r\n");
      out.write("\t<section id=\"contact\" class=\"section green\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2><b>Central Authority Login</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"blankdivider30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cform\" id=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <div id=\"sendmessage\">Your message has been sent. Thank you!</div> -->\r\n");
      out.write("\t\t\t\t\t\t<!-- <div id=\"errormessage\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <form  class=\"login-page\" name=\"f1\" id=\"login\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/AdminLogin\"> \r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" data-rule=\"minlen:4\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-email form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"password\" id=\"email\" placeholder=\"Your Password\" data-rule=\"email\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Send message\" class=\"btn btn-theme pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ./span12 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- dataowner section -->\r\n");
      out.write("\t<section id=\"services\" class=\"section green\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2><b>Owner Login</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"blankdivider30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cform\" id=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t<!-- \t<div id=\"sendmessage\">Your message has been sent. Thank you!</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"errormessage\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <form  class=\"login-page\" name=\"f1\" id=\"login\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/DataOwnerLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" data-rule=\"minlen:4\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-email form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"password\" id=\"email\" placeholder=\"Your Password\" data-rule=\"email\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Send message\" class=\"btn btn-theme pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ./span12 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \tUser Login section -->\r\n");
      out.write("<section id=\"works\" class=\"section green\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2><b>User Login</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"blankdivider30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cform\" id=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <div id=\"sendmessage\">Your message has been sent. Thank you!</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"errormessage\"></div> -->\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  <form name=\"f1\" id=\"login\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/select_identytocken.jsp\"> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-email form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"password\" id=\"email\" placeholder=\"Your Password\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Send message\" class=\"btn btn-theme pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ./span12 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \tUser Registration Section -->\r\n");
      out.write("<section id=\"working\" class=\"section green\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2><b>User Registration </b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"blankdivider30\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"cform\" id=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <div id=\"sendmessage\">Your message has been sent. Thank you!</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"errormessage\"></div> -->\r\n");
      out.write("\t\t\t\t\t\t \t<form action=\"");
      out.print(request.getContextPath());
      out.write("/NewUser\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userid\" class=\"form-control\" id=\"name\" placeholder=\"Your UserId\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-email form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"password\" id=\"email\" placeholder=\"Your Password\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select  name=\"domain\" required=\"yes\" class=\"form-control\" style=\"width: 570px;height:60px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\" class=\"form-control\" style=\"width: 570px;height:60px;\">Domain Code</option>\r\n");
      out.write("\t\t\t\t\t\t");


	String value;
	String name="";
 	Connection connection = null;
 	Statement statement = null;
 	ResultSet resultSet = null;
 	UserDAO userDAO=null;
	DAO dao=DAO.getInstance();
	connection=dao.connector();
	statement = connection.createStatement();
	resultSet = statement.executeQuery("select domain_code,domain_name from m_domain");
		while(resultSet.next())
		{
			value=resultSet.getString(1);
			name=resultSet.getString(2);
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(value);
      out.write("\" style=\"width: 570px;height:60px;\">");
      out.print(name);
      out.write("</option>\r\n");
      out.write("\t\t\t");
 
		
		}


	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-name form-group\">\r\n");
      out.write("\t\t\t\t<select  name=\"subdomain\" required=\"yes\" class=\"form-control\" style=\"width: 570px;height:60px;\">\r\n");
      out.write("\t\t\t\t<option value=\"\" class=\"form-control\" style=\"width: 570px;height:60px;\">Sub Domain Code</option>\r\n");
      out.write("\t\t\t\t\t\t");


	String sub_code;
 	String sd_name="";
 	UserDAO userDAO1=null;
	DAO dao1=DAO.getInstance();
	connection=dao.connector();
	statement = connection.createStatement();
	resultSet = statement.executeQuery("select sdomain_code,sdomain_name from m_subdomain");
		while(resultSet.next())
		{
			sub_code=resultSet.getString(1);
			sd_name=resultSet.getString(2);
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(sub_code);
      out.write("\" style=\"width: 570px;height:60px;\">");
      out.print(sd_name);
      out.write("</option>\r\n");
      out.write("\t\t\t");
 
		
		}


	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field your-email form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"Your Email\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"validation\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <button class=\"btn btn-theme pull-left\">Register</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <input type=\"submit\" value=\"Send message\" class=\"btn btn-theme pull-left\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ./span12 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span><b>Email id: </b>info@dhsinformatics.com</span></br>\r\n");
      out.write("                 <span><b>Contact No: </b>9886692401</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ./container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<a href=\"#\" class=\"scrollup\"><i class=\"icon-angle-up icon-square icon-bgdark icon-2x\"></i></a>\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.scrollTo.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.nav.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.localScroll.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t<script src=\"js/isotope.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t<script src=\"js/inview.js\"></script>\r\n");
      out.write("\t<script src=\"js/animate.js\"></script>\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("\t<script src=\"contactform/contactform.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
